# Generated by Django 4.1.1 on 2022-09-26 10:09

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='normaluser',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
