# Generated by Django 4.1.1 on 2022-09-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_normaluser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='normaluser',
            managers=[
            ],
        ),
    ]
