# Generated by Django 4.1.1 on 2022-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adminuser_is_admin_alter_adminuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('adv', models.BooleanField(verbose_name='adv_accept')),
                ('permission', models.BooleanField(verbose_name='permission_accept')),
                ('check_email', models.BooleanField(verbose_name='cheking_email')),
            ],
            options={
                'verbose_name': 'normal_user',
                'verbose_name_plural': 'normal_users',
                'db_table': 'normal_user',
            },
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'admin_user', 'verbose_name_plural': 'admin_users'},
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_user',
        ),
    ]
