# Generated by Django 4.1.1 on 2022-09-23 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_normaluser_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='8자 이상 입력해주세요..!')], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='8자 이상 입력해주세요..!')], verbose_name='password'),
        ),
    ]
